# Generated by Django 3.1.4 on 2021-01-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_auto_20210102_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweets.tweet",
            ),
        ),
    ]
