# Generated by Django 3.1.5 on 2021-01-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_tweet_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweets.tweet",
            ),
        ),
    ]
